

class ExistsError(BaseException):
    pass


class NotExistsError(BaseException):
    pass
